# Generated by Django 6.0.5 on 2026-05-26 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('parse_status', models.CharField(default='SUCCESS', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.rawupload')),
            ],
        ),
        migrations.CreateModel(
            name='SourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'UTILITY'), ('TRAVEL', 'TRAVEL')], max_length=20)),
                ('ingestion_method', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.AddField(
            model_name='rawupload',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.sourceconfig'),
        ),
    ]
