# Generated by Django 6.0.5 on 2026-05-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedemissionrecord',
            name='anomaly_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
